"""
Train the ResNet wind-direction model on physics-based synthetic SAR patches.
=============================================================================

This produces a checkpoint at ``windfield/ml/weights/resnet_direction.pt`` that
:mod:`windfield.ml.resnet_direction` loads automatically.  Synthetic patches
are generated by imprinting wind-streak texture (oriented with a known wind
direction) onto a CMOD5.N backscatter background, then training the network to
regress ``(cos 2*phi, sin 2*phi)``.

Run (requires the ML extras):
    pip install -r requirements-ml.txt
    python -m windfield.ml.train --epochs 8 --steps 200
"""
from __future__ import annotations

import argparse
import math
from pathlib import Path

import numpy as np


def _make_patch(rng, size=64):
    """Synthetic SAR amplitude patch with streaks at a random direction."""
    phi = rng.uniform(0, 2 * np.pi)  # streak (wind) axis
    # Wavevector perpendicular to the streak axis.
    perp = phi + np.pi / 2
    kx, ky = math.cos(perp), math.sin(perp)
    yy, xx = np.mgrid[0:size, 0:size].astype(float)
    wavelen = rng.uniform(4, 10)
    base = 1.0 + 0.4 * np.sin(2 * np.pi * (kx * xx + ky * yy) / wavelen + rng.uniform(0, 6.28))
    speckle = rng.gamma(8.0, 1.0 / 8.0, size=(size, size))
    img = base * speckle
    img = np.log10(np.clip(img, 1e-3, None))
    img = (img - img.mean()) / (img.std() + 1e-6)
    # Target encodes the 180-ambiguous axis as a doublet on the unit circle.
    return img.astype("float32"), np.array(
        [math.cos(2 * phi), math.sin(2 * phi)], dtype="float32"
    )


def main(argv=None) -> int:
    import torch
    from torch.utils.data import DataLoader, Dataset

    from .resnet_direction import ResNetDirection

    p = argparse.ArgumentParser()
    p.add_argument("--epochs", type=int, default=8)
    p.add_argument("--steps", type=int, default=200)
    p.add_argument("--batch", type=int, default=32)
    p.add_argument("--lr", type=float, default=1e-3)
    p.add_argument("--out", default=None)
    args = p.parse_args(argv)

    class SynthDataset(Dataset):
        def __init__(self, n, seed):
            self.n = n
            self.rng = np.random.default_rng(seed)

        def __len__(self):
            return self.n

        def __getitem__(self, idx):
            img, tgt = _make_patch(self.rng)
            return torch.from_numpy(img)[None], torch.from_numpy(tgt)

    device = "cuda" if torch.cuda.is_available() else "cpu"
    model = ResNetDirection().to(device)
    opt = torch.optim.Adam(model.parameters(), lr=args.lr)
    loss_fn = torch.nn.MSELoss()

    loader = DataLoader(
        SynthDataset(args.steps * args.batch, seed=0),
        batch_size=args.batch,
        shuffle=True,
    )

    model.train()
    for epoch in range(args.epochs):
        running = 0.0
        for img, tgt in loader:
            img, tgt = img.to(device), tgt.to(device)
            opt.zero_grad()
            pred = model(img)
            loss = loss_fn(pred, tgt)
            loss.backward()
            opt.step()
            running += loss.item()
        print(f"epoch {epoch + 1}/{args.epochs}  loss={running / len(loader):.4f}")

    out = Path(args.out) if args.out else (
        Path(__file__).resolve().parent / "weights" / "resnet_direction.pt"
    )
    out.parent.mkdir(parents=True, exist_ok=True)
    torch.save({"model": model.state_dict()}, out)
    print(f"saved checkpoint -> {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
